# Site settings
title: Adrian Danao-Schroeder
description: 'Aerospace Engineering and Chinese Double Major at the University of Maryland College Park'
url: "andanao.github.io/Personal-Site/"
baseurl: 
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Adrian Danao Schroeder'
  email: adriandanao@gmail.com
#  twitter_username: adrian.danao
#  facebook_username: [wee](/assets/A_Danao-Schroeder_resume_2019-02.pdf)
  github_username:  andanao
  linkedin_username:  adrian-danao-schroeder-a85698155
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_di\: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
